// <auto-generated />
using System;
using BinaryBrainsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BinaryBrainsAPI.Migrations
{
    [DbContext(typeof(ArtechDbContext))]
    [Migration("20211017214921_PurchasesTable")]
    partial class PurchasesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.ArtClass", b =>
                {
                    b.Property<int>("ArtClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtClassDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArtClassEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtClassImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArtClassStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArtClassTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ClassLimit")
                        .HasColumnType("int");

                    b.Property<double>("ClassPrice")
                        .HasColumnType("float");

                    b.Property<int?>("ClassTeacherID")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationID")
                        .HasColumnType("int");

                    b.Property<int>("RefundDayLimit")
                        .HasColumnType("int");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("ArtClassID");

                    b.HasIndex("ArtClassTypeID");

                    b.HasIndex("ClassTeacherID");

                    b.HasIndex("OrganisationID");

                    b.HasIndex("VenueID");

                    b.ToTable("ArtClass");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.ArtClassAnnouncement", b =>
                {
                    b.Property<int>("ArtClassAnnouncementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtClassAnnouncementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArtClassID")
                        .HasColumnType("int");

                    b.HasKey("ArtClassAnnouncementID");

                    b.HasIndex("ArtClassID");

                    b.ToTable("ArtClassAnnouncement");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.ArtClassType", b =>
                {
                    b.Property<int>("ArtClassTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtClassTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtClassTypeID");

                    b.ToTable("ArtClassType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.ClassTeacher", b =>
                {
                    b.Property<int>("ClassTeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeacherEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherPhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TeacherSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherTypeID")
                        .HasColumnType("int");

                    b.HasKey("ClassTeacherID");

                    b.HasIndex("TeacherTypeID");

                    b.ToTable("ClassTeacher");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtClassID")
                        .HasColumnType("int");

                    b.Property<double>("DifficultyRating")
                        .HasColumnType("float");

                    b.Property<string>("FeedbackComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverallRating")
                        .HasColumnType("float");

                    b.Property<double>("TeacherRating")
                        .HasColumnType("float");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.HasIndex("ArtClassID");

                    b.HasIndex("UserID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.TeacherType", b =>
                {
                    b.Property<int>("TeacherTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeacherTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherTypeID");

                    b.ToTable("TeacherType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artists.Invitation", b =>
                {
                    b.Property<int>("InvitationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExhibitionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvitationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvitationStatusID")
                        .HasColumnType("int");

                    b.HasKey("InvitationID");

                    b.HasIndex("ExhibitionID");

                    b.HasIndex("InvitationStatusID");

                    b.ToTable("Invitation");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artists.InvitationStatus", b =>
                {
                    b.Property<int>("InvitationStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InvitationStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvitationStatusID");

                    b.ToTable("InvitationStatus");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artworks.Artwork", b =>
                {
                    b.Property<int>("ArtworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtworkDimensionID")
                        .HasColumnType("int");

                    b.Property<string>("ArtworkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ArtworkPrice")
                        .HasColumnType("float");

                    b.Property<int?>("ArtworkStatusID")
                        .HasColumnType("int");

                    b.Property<string>("ArtworkTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArtworkTypeID")
                        .HasColumnType("int");

                    b.Property<int>("FrameColourID")
                        .HasColumnType("int");

                    b.Property<int>("MediumTypeID")
                        .HasColumnType("int");

                    b.Property<int>("SurfaceTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ArtworkID");

                    b.HasIndex("ArtworkDimensionID");

                    b.HasIndex("ArtworkStatusID");

                    b.HasIndex("ArtworkTypeID");

                    b.HasIndex("FrameColourID");

                    b.HasIndex("MediumTypeID");

                    b.HasIndex("SurfaceTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("Artwork");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artworks.ArtworkDimension", b =>
                {
                    b.Property<int>("ArtworkDimensionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtworkDimensionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtworkDimensionID");

                    b.ToTable("ArtworkDimension");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artworks.ArtworkStatus", b =>
                {
                    b.Property<int>("ArtworkStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtworkStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtworkStatusID");

                    b.ToTable("ArtworkStatus");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artworks.ArtworkType", b =>
                {
                    b.Property<int>("ArtworkTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtworkTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtworkTypeID");

                    b.ToTable("ArtworkType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artworks.FrameColour", b =>
                {
                    b.Property<int>("FrameColourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FrameColourDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FrameColourID");

                    b.ToTable("FrameColour");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artworks.MediumType", b =>
                {
                    b.Property<int>("MediumTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MediumTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MediumTypeID");

                    b.ToTable("MediumType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artworks.SurfaceType", b =>
                {
                    b.Property<int>("SurfaceTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SurfaceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurfaceTypeID");

                    b.ToTable("SurfaceType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Bookings.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtClassID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BookingNotificationID")
                        .HasColumnType("int");

                    b.Property<string>("BookingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("ArtClassID");

                    b.HasIndex("BookingNotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Bookings.BookingNotification", b =>
                {
                    b.Property<int>("BookingNotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookNotificationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingNotificationID");

                    b.ToTable("BookingNotification");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.BridgeEntities.ExhibitionArtwork", b =>
                {
                    b.Property<int>("ExhibitionArtworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArtworkID")
                        .HasColumnType("int");

                    b.Property<int?>("ExhibitionID")
                        .HasColumnType("int");

                    b.HasKey("ExhibitionArtworkID");

                    b.HasIndex("ArtworkID");

                    b.HasIndex("ExhibitionID");

                    b.ToTable("ExhibitionArtwork");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.BridgeEntities.UserInvitation", b =>
                {
                    b.Property<int>("UserInvitationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InvitationID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserInvitationID");

                    b.HasIndex("InvitationID");

                    b.HasIndex("UserID");

                    b.ToTable("UserInvitation");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.BridgeEntities.UserTypePrivilege", b =>
                {
                    b.Property<int>("UserTypePrivilegeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PrivilegesID")
                        .HasColumnType("int");

                    b.Property<int?>("UserTypeID")
                        .HasColumnType("int");

                    b.HasKey("UserTypePrivilegeID");

                    b.HasIndex("PrivilegesID");

                    b.HasIndex("UserTypeID");

                    b.ToTable("UserTypePrivilege");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExhibitionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExhibitionEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExhibitionImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExhibitionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExhibitionStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExhibitionTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("OrganisationID")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleID")
                        .HasColumnType("int");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("ExhibitionID");

                    b.HasIndex("ExhibitionTypeID");

                    b.HasIndex("OrganisationID");

                    b.HasIndex("ScheduleID");

                    b.HasIndex("VenueID");

                    b.ToTable("Exhibition");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.ApplicationStatus", b =>
                {
                    b.Property<int>("ApplicationStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationStatusID");

                    b.ToTable("ApplicationStatus");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.ApplicationTag", b =>
                {
                    b.Property<int>("ApplicationTagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationArtworkTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationDimension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExhibitionApplicationID")
                        .HasColumnType("int");

                    b.Property<int?>("ExhibitionID")
                        .HasColumnType("int");

                    b.Property<string>("Medium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationTagID");

                    b.HasIndex("ExhibitionApplicationID");

                    b.HasIndex("ExhibitionID");

                    b.ToTable("ApplicationTag");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.ExhibitionAnnouncement", b =>
                {
                    b.Property<int>("ExhibitionAnnouncementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExhibitionAnnouncementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExhibitionID")
                        .HasColumnType("int");

                    b.HasKey("ExhibitionAnnouncementID");

                    b.HasIndex("ExhibitionID");

                    b.ToTable("ExhibitionAnnouncement");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.ExhibitionApplication", b =>
                {
                    b.Property<int>("ExhibitionApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApplicationStatusID")
                        .HasColumnType("int");

                    b.Property<string>("ExhibitionApplicationImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExhibitionApplicationImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExhibitionApplicationImage3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExhibitionID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ExhibitionApplicationID");

                    b.HasIndex("ApplicationStatusID");

                    b.HasIndex("ExhibitionID");

                    b.HasIndex("UserID");

                    b.ToTable("ExhibitionApplication");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.ExhibitionType", b =>
                {
                    b.Property<int>("ExhibitionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExhibitionTypeDecription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExhibitionTypeID");

                    b.ToTable("ExhibitionType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.Organisation", b =>
                {
                    b.Property<int>("OrganisationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrganisationalAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganisationalName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganisationID");

                    b.ToTable("Organisation");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ScheduleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleTypeID")
                        .HasColumnType("int");

                    b.HasKey("ScheduleID");

                    b.HasIndex("ScheduleTypeID");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.ScheduleType", b =>
                {
                    b.Property<int>("ScheduleTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ScheduleTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduleTypeID");

                    b.ToTable("ScheduleType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.Venue", b =>
                {
                    b.Property<int>("VenueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VenueDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenueID");

                    b.ToTable("Venue");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Images.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ImageContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ImageTypeID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("ImageTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Images.ImageType", b =>
                {
                    b.Property<int>("ImageTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageTypeID");

                    b.ToTable("ImageType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Payments.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("CardHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefundID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("BookingID");

                    b.HasIndex("RefundID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Payments.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaymentStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentStatusID");

                    b.ToTable("PaymentStatus");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Payments.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaymentTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTypeID");

                    b.ToTable("PaymentType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Payments.Purchases", b =>
                {
                    b.Property<int>("PurchasesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArtworkID")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PurchasesID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Payments.Refund", b =>
                {
                    b.Property<int>("RefundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtClassRefunded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefundStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefundID");

                    b.ToTable("Refund");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.Announcement", b =>
                {
                    b.Property<int>("AnnouncementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AnnounceStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnnouncementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnnouncementTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnnouncementID");

                    b.ToTable("Announcement");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceID")
                        .HasColumnType("int");

                    b.HasKey("CityID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.Privileges", b =>
                {
                    b.Property<int>("PrivilegesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PrivilegeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivilegeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrivilegesID");

                    b.ToTable("Privileges");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.Province", b =>
                {
                    b.Property<int>("ProvinceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceID");

                    b.HasIndex("CountryID");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.Suburb", b =>
                {
                    b.Property<int>("SuburbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("SuburbName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuburbID");

                    b.HasIndex("CityID");

                    b.ToTable("Suburb");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.Timer", b =>
                {
                    b.Property<int>("TimerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TimerSet")
                        .HasColumnType("int");

                    b.HasKey("TimerID");

                    b.ToTable("Timer");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtistBio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuburbID")
                        .HasColumnType("int");

                    b.Property<string>("UserAddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserDOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserPostalCode")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.HasIndex("UserTypeID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.UserType", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PrivilegesID")
                        .HasColumnType("int");

                    b.Property<string>("UserRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserTypeID");

                    b.HasIndex("PrivilegesID");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.ArtClass", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.ArtClasses.ArtClassType", "ArtClassType")
                        .WithMany()
                        .HasForeignKey("ArtClassTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.ArtClasses.ClassTeacher", "ClassTeacher")
                        .WithMany()
                        .HasForeignKey("ClassTeacherID");

                    b.HasOne("BinaryBrainsAPI.Entities.Exhibitions.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Exhibitions.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtClassType");

                    b.Navigation("ClassTeacher");

                    b.Navigation("Organisation");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.ArtClassAnnouncement", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.ArtClasses.ArtClass", "ArtClass")
                        .WithMany()
                        .HasForeignKey("ArtClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtClass");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.ClassTeacher", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.ArtClasses.TeacherType", "TeacherType")
                        .WithMany()
                        .HasForeignKey("TeacherTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.ArtClasses.Feedback", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.ArtClasses.ArtClass", "ArtClass")
                        .WithMany()
                        .HasForeignKey("ArtClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtClass");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artists.Invitation", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Artists.InvitationStatus", "InvitationStatus")
                        .WithMany()
                        .HasForeignKey("InvitationStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibition");

                    b.Navigation("InvitationStatus");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Artworks.Artwork", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Artworks.ArtworkDimension", "ArtworkDimension")
                        .WithMany()
                        .HasForeignKey("ArtworkDimensionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Artworks.ArtworkStatus", "ArtworkStatus")
                        .WithMany()
                        .HasForeignKey("ArtworkStatusID");

                    b.HasOne("BinaryBrainsAPI.Entities.Artworks.ArtworkType", "ArtworkType")
                        .WithMany()
                        .HasForeignKey("ArtworkTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Artworks.FrameColour", "FrameColour")
                        .WithMany()
                        .HasForeignKey("FrameColourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Artworks.MediumType", "MediumType")
                        .WithMany()
                        .HasForeignKey("MediumTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Artworks.SurfaceType", "SurfaceType")
                        .WithMany()
                        .HasForeignKey("SurfaceTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("ArtworkDimension");

                    b.Navigation("ArtworkStatus");

                    b.Navigation("ArtworkType");

                    b.Navigation("FrameColour");

                    b.Navigation("MediumType");

                    b.Navigation("SurfaceType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Bookings.Booking", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.ArtClasses.ArtClass", "ArtClass")
                        .WithMany()
                        .HasForeignKey("ArtClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Bookings.BookingNotification", "BookingNotification")
                        .WithMany()
                        .HasForeignKey("BookingNotificationID");

                    b.HasOne("BinaryBrainsAPI.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtClass");

                    b.Navigation("BookingNotification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.BridgeEntities.ExhibitionArtwork", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Artworks.Artwork", "Artwork")
                        .WithMany()
                        .HasForeignKey("ArtworkID");

                    b.HasOne("BinaryBrainsAPI.Entities.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionID");

                    b.Navigation("Artwork");

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.BridgeEntities.UserInvitation", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Artists.Invitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("InvitationID");

                    b.HasOne("BinaryBrainsAPI.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Invitation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.BridgeEntities.UserTypePrivilege", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Users.Privileges", "Privileges")
                        .WithMany()
                        .HasForeignKey("PrivilegesID");

                    b.HasOne("BinaryBrainsAPI.Entities.Users.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeID");

                    b.Navigation("Privileges");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibition", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Exhibitions.ExhibitionType", "ExhibitionType")
                        .WithMany()
                        .HasForeignKey("ExhibitionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Exhibitions.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationID");

                    b.HasOne("BinaryBrainsAPI.Entities.Exhibitions.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleID");

                    b.HasOne("BinaryBrainsAPI.Entities.Exhibitions.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExhibitionType");

                    b.Navigation("Organisation");

                    b.Navigation("Schedule");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.ApplicationTag", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Exhibitions.ExhibitionApplication", "ExhibitionApplication")
                        .WithMany()
                        .HasForeignKey("ExhibitionApplicationID");

                    b.HasOne("BinaryBrainsAPI.Entities.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionID");

                    b.Navigation("Exhibition");

                    b.Navigation("ExhibitionApplication");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.ExhibitionAnnouncement", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.ExhibitionApplication", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Exhibitions.ApplicationStatus", "ApplicationStatus")
                        .WithMany()
                        .HasForeignKey("ApplicationStatusID");

                    b.HasOne("BinaryBrainsAPI.Entities.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionID");

                    b.HasOne("BinaryBrainsAPI.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("ApplicationStatus");

                    b.Navigation("Exhibition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Exhibitions.Schedule", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Exhibitions.ScheduleType", "ScheduleType")
                        .WithMany()
                        .HasForeignKey("ScheduleTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Images.Image", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Images.ImageType", "ImageType")
                        .WithMany()
                        .HasForeignKey("ImageTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Payments.Payment", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Bookings.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinaryBrainsAPI.Entities.Payments.Refund", "Refund")
                        .WithMany()
                        .HasForeignKey("RefundID");

                    b.Navigation("Booking");

                    b.Navigation("Refund");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.City", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Users.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.Province", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Users.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.Suburb", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Users.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.User", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Users.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("BinaryBrainsAPI.Entities.Users.UserType", b =>
                {
                    b.HasOne("BinaryBrainsAPI.Entities.Users.Privileges", "Privileges")
                        .WithMany()
                        .HasForeignKey("PrivilegesID");

                    b.Navigation("Privileges");
                });
#pragma warning restore 612, 618
        }
    }
}
